name: mini-cloud

services:
  backend:
    platform: linux/arm64
    image: nojjen/vigilant-carnival:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    platform: linux/arm64
    image: nojjen/fuzzy-broccoli:latest
    depends_on:
      - backend

  nginx:
    image: nginx:1-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    #secrets:
     #- postgres_password

  adminer:
    image: adminer
    restart: always

#secrets:
  #postgres_password:
    #file: db/password.txt

volumes:
  postgres_data:
    driver: local
